<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * NotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaRepository extends EntityRepository
{

}
