app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
#Login
login:
    path:     /login
    defaults: { _controller: AppBundle:Usuario:login }

login_check:
    path: /login_check
logout:
    path: /logout