# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        my_db_provider:
            entity:
                class:  AppBundle:Usuario
                property: username

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path: logout
                target: /login

    access_control:
        - { path: ^/login,  roles:  IS_AUTHENTICATED_ANONYMOUSLY }